---
- name: Install PHP other packages
  yum: name={{ item }} state=present
  with_items:
    - php-mysqlnd
    - php-pdo
    - php-gd
    - php-ldap
    - php-odbc
    - php-pear
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-soap
    - phpMyAdmin