---
- name: Yum update
  yum: name=* state=latest

- name: Install PHP Apache
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - curl
    - curl-devel
    - epel-release

- name: Get mysql community edition
  yum:  name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state=present

- name: install mysql CE
  yum: name=mysql-server state=present

- name: install MySql-Python
  yum: name=MySQL-python state=present